### PR TITLE
Fix cond statement

### PR DESCRIPTION
**Pull request by dbernheisel**
Unfortunately #52 had a syntax error :(
Fixing that here.

### CODE REVIEW

**Comment by drapergeek** [comment]
@dbernheisel does this require `true`, it won't accept the "any" option that we were trying? Just trying to follow what happened here.

**Comment by dbernheisel** [comment]
@drapergeek I think you're thinking of `case`, this is `cond`, and the fallback option for cond needs to be truthy, and idiomatically `true`.

**Comment by dbernheisel** [comment]
[Here's the error:](https://circleci.com/gh/thoughtbot/formulator/193?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

```
== Compilation error in file lib/formulator/input.ex ==
** (CompileError) lib/formulator/input.ex:50: unbound variable _ inside "cond". If you want the last clause to always match, you probably meant to use: true ->
    lib/formulator/input.ex:45: (module)
Exited with code 1
```

**Comment by drapergeek** [comment]
😢 


:shipit:

**Pull request merged**
